version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: cargo_admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cargo_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Backend/psql.sql:/docker-entrypoint-initdb.d/psql.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cargo_admin -d cargo_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - cargo-network

  backend:
    build: ./Backend
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=cargo_db
      - DB_USER=cargo_admin
      - DB_PASSWORD=admin
      - DB_PORT=5432
    depends_on:
      db:
        condition: service_healthy
    networks:
      - cargo-network

  

  frontend:
    build: ./Frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:8000/api
    depends_on:
      - backend
    networks:
      - cargo-network

volumes:
  postgres_data:

networks:
  cargo-network:
    driver: bridge